import { Discount } from "@/types/product";

export const dummyDiscounts: Discount[] = [
  {
    id: "1",
    _id: "1",
    sellerId: "507f1f77bcf86cd799439011",
    discountName: "Welcome 10",
    method: "discount_code",
    discountCode: "WELCOME10",
    couponCode: "WELCOME10",
    discountType: "fixed",
    discountValue: 10,
    type: "coupon",
    value: 10,
    appliesTo: "all_orders",
    applyFor: "all_orders",
    productIds: [],
    categoryIds: [],
    subcategoryIds: [],
    availableOnAllSalesChannels: true,
    eligibility: "all_customers",
    customerSegmentIds: [],
    customerIds: [],
    description: "Flat 10 EGP off on your first order",
    startDate: "2025-10-01",
    startTime: "00:00",
    endDate: "2025-10-31",
    endTime: "23:59",
    active: true,
    status: "active",
    store: "fashion",
    canUseWithPromotion: false,
    canUseWithFlashSale: false,
    isUnlimited: true,
    applyViaUrl: false,
    displayAtCheckout: true,
    neverExpired: false,
  },
  {
    id: "2",
    _id: "2",
    sellerId: "default_seller",
    discountName: "Free Shipping 15",
    method: "discount_code",
    discountCode: "FREESHIP15",
    couponCode: "FREESHIP15",
    discountType: "shipping",
    discountValue: 15,
    type: "coupon",
    value: 15,
    appliesTo: "all_orders",
    applyFor: "all_orders",
    productIds: [],
    categoryIds: [],
    subcategoryIds: [],
    availableOnAllSalesChannels: true,
    eligibility: "all_customers",
    customerSegmentIds: [],
    customerIds: [],
    description: "Free shipping up to 15 EGP",
    startDate: "2025-10-01",
    startTime: "00:00",
    endDate: "2025-12-31",
    endTime: "23:59",
    active: true,
    status: "active",
    store: "default",
    canUseWithPromotion: true,
    canUseWithFlashSale: true,
    isUnlimited: false,
    applyViaUrl: true,
    displayAtCheckout: false,
    neverExpired: true,
  },
  {
    id: "3",
    _id: "3",
    sellerId: "electronics_seller",
    discountName: "Save 30",
    method: "automatic_discount",
    discountCode: "SAVE30",
    couponCode: "SAVE30",
    discountType: "percentage",
    discountValue: 30,
    type: "promotion",
    value: 30,
    appliesTo: "specific_products",
    applyFor: "specific_products",
    productIds: ["1", "2"],
    categoryIds: [],
    subcategoryIds: [],
    availableOnAllSalesChannels: true,
    eligibility: "all_customers",
    customerSegmentIds: [],
    customerIds: [],
    description: "30% off on selected products",
    startDate: "2025-10-05",
    startTime: "00:00",
    endDate: "2025-11-05",
    endTime: "23:59",
    active: true,
    status: "scheduled",
    store: "electronics",
    canUseWithPromotion: false,
    canUseWithFlashSale: false,
    isUnlimited: false,
    applyViaUrl: true,
    displayAtCheckout: true,
    neverExpired: false,
  },
  {
    id: "4",
    _id: "4",
    sellerId: "fashion_seller",
    discountName: "Big Sale 2025",
    method: "automatic_discount",
    discountCode: "BIGSALE2025",
    couponCode: "BIGSALE2025",
    discountType: "percentage",
    discountValue: 50,
    type: "promotion",
    value: 50,
    appliesTo: "all_orders",
    applyFor: "all_orders",
    productIds: [],
    categoryIds: [],
    subcategoryIds: [],
    availableOnAllSalesChannels: true,
    eligibility: "all_customers",
    customerSegmentIds: [],
    customerIds: [],
    description: "50% off sitewide for limited time",
    startDate: "2025-11-01",
    startTime: "00:00",
    endDate: "2025-11-10",
    endTime: "23:59",
    active: true,
    status: "active",
    store: "fashion",
    canUseWithPromotion: true,
    canUseWithFlashSale: true,
    isUnlimited: false,
    applyViaUrl: false,
    displayAtCheckout: true,
    neverExpired: false,
  },
];
